language: elixir
elixir: '1.11.4'
otp_release: '23.0'
env:
  - MIX_ENV=test
script:
  - mix format --check-formatted
  - mix credo --all
  - mix test
  - mix coveralls.travis
cache:
  directories:
    - deps
    - _build
