language: elixir
elixir: '1.7.0'
otp_release: '20.3'
env:
  - MIX_ENV=test
script:
  - mix format --check-formatted
  - mix credo --all
  - mix test
  - mix coveralls.travis
cache:
  directories:
    - deps
    - _build
